---
- name: Ensure MAS is installed.
  homebrew: name=mas state=present

- name: Get MAS account status
  shell: 'mas account'
  register: mas_account_result
  failed_when: mas_account_result.rc > 0
  changed_when: false

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ mas_installed_apps + mas_installed_app_ids }}"
  when: "'{{ item.id|default(item) }}' not in mas_list.stdout"

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: mas_upgrade_all_apps
